---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[animapp::kitchen_test]
      - recipe[animapp::default]
    attributes:
